name: Deploy coverage to GitHub Pages

on:
  push:
    branches: [ main ]              # run on pushes to main
  workflow_dispatch: {}

permissions:
  pages: write       # required to deploy
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install epitech_console
        run: |
          echo "y" | pip uninstall epitech_console || true
          pip install -e .
      - name: Test with pytest (html)
        run: |
          pytest --cov=epitech_console --cov-report=html --cov-report=term-missing
      - name: Upload coverage report (html)
        uses: actions/upload-pages-artifact@v4
        with:
          path: htmlcov

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-deploy
    environment:
      name: github-pages
      url: https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
